spring:
    application:
        name: utilisateur-service
    datasource:
        url: jdbc:mysql://localhost:3306/buguser 
        username: root
        password: root
    cloud:
        discovery:
           enabled: false
server:    
    port: 9092