spring:
    application:
        name: chat-service
    data:
        mongodb:
            host: localhost
            port: 27017
            database: talkhours
            auto-index-creation: true

    cloud:
        discovery:
           enabled: true
server:    
    port: 9091